name: Flappy Bird Pixel Animation

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

permissions:
  contents: write   # <- WAJIB biar bisa push

jobs:
  animate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate frame
        run: |
          FRAME=$(( $(date +%s) % 4 ))
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="150">
            <rect width="100%" height="100%" fill="skyblue"/>
            <rect x="150" y="0" width="20" height="50" fill="green"/>
            <rect x="150" y="100" width="20" height="50" fill="green"/>
          ' > flappy-bird.svg
          if [ $FRAME -eq 0 ]; then
            echo '<rect x="40" y="60" width="10" height="10" fill="yellow"/>
                  <rect x="50" y="65" width="5" height="5" fill="white"/>' >> flappy-bird.svg
          elif [ $FRAME -eq 1 ]; then
            echo '<rect x="40" y="65" width="10" height="10" fill="yellow"/>
                  <rect x="50" y="70" width="5" height="5" fill="white"/>' >> flappy-bird.svg
          elif [ $FRAME -eq 2 ]; then
            echo '<rect x="40" y="70" width="10" height="10" fill="yellow"/>
                  <rect x="50" y="75" width="5" height="5" fill="white"/>' >> flappy-bird.svg
          else
            echo '<rect x="40" y="65" width="10" height="10" fill="yellow"/>
                  <rect x="50" y="60" width="5" height="5" fill="white"/>' >> flappy-bird.svg
          fi
          echo '</svg>' >> flappy-bird.svg

      - name: Commit frame
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add flappy-bird.svg
          git commit -m "update flappy bird frame" || echo "no changes"
          git push