name: GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: username-mu # Ganti dengan username GitHub-mu
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_from: 30
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_introduction: yes
          plugin_introduction_title: yes
          template: classic
          output: github-metrics.svg
